### ISSUE TITLE
Coursework 2 Uniform Laplace operator

### ISSUE THREAD

**Issue by hanyang1996** [smartgeometry-ucl/compM080-compGV18-2019#10]
Hi!

I have a question about uniform Laplace operator. Which form of uniform Laplace operator should we use in coursework? The one with all one diagonal like `[1,-0.5,0,-0.5; -0.5, 1, -0.5, 0; 0, -0.5, 1, -0.5; -0.5, 0, -0.5, 1]` or the one with negative values on diagonal and with ones in other places like `[-2,1,0,1; 1, -2, 1, 0; 0, 1, -2, 1; 1, 0, 1, -2]`? 

Thanks!

Best wishes,

Han

**Comment by yushiangw** [comment]
Hi Han,
It should be 1 along diagonal and -1/k_i for the off-diagonal terms with k_i being the valence for vertex v_i. Like the form shows in 05.smoothing slides.

**Comment by yushiangw** [comment]
Hi Han,
For the record, in our slide, it's -1 along diagonal and 1/k_i for the off-diagonal terms but it will not affect mean curvature visualization.

**Comment by hanyang1996** [comment]
Thanks very much yushiang!
