### ISSUE TITLE
Ubuntu/python/pip/pyglet issue

### ISSUE THREAD

**Issue by vincetrencsenyi** [smartgeometry-ucl/compM080-compGV18-2019#11]
Hi. An update for pip was installed which broke it for me. 
File "/usr/bin/pip", line 9, in <module>
from pip import main
ImportError: cannot import name main

I need to install pyglet to do the coursework, but I cant figure out how to fix pip.

**Comment by yushiangw** [comment]
a new anaconda installation or environment may solve the problem. https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html?highlight=environment#creating-an-environment-with-commands

otherwise using MeshLab for visualization is also an option
