### ISSUE TITLE
Python/Ubuntu import_OBJ not working with cube.obj

### ISSUE THREAD

**Issue by vincetrencsenyi** [smartgeometry-ucl/compM080-compGV18-2019#12]
Hello, 

the provided import_OBJ function does not seem to work with the cube.obj file. It runs into an index out of bounds error at line 31, p = .... .
The function does work with the camelhead file, however.

EDIT: I looked in the file source, now I see why

**Comment by preddy5** [comment]
Hey @vincetrencsenyi we have added a new set of meshes without textures, could you use cube.obj from the set.
