### ISSUE TITLE
CW2 Problem with cow and cow_manifold mesh

### ISSUE THREAD

**Issue by hanyang1996** [smartgeometry-ucl/compM080-compGV18-2019#14]
Hello!

I have a question about the given meshes. When computing the eigenvalues of cow and cow_manifold meshes, I used the equation given in FAQ_5 to require the smallest eigenvalues. 

As mentioned by Niloy this morning, the smallest eigenvalue should be zero (numerical zero). However, I found that both cow of cow_manifold meshes have negative smallest eigenvalues and this should not be the case. I believe my implementation is correct since the bunny mesh always gives me the zero as the smallest eigenvalue. I guess the problem is still due to the tail area of the cow (one is around 620th vertex I think).  Maybe the reason is that the mesh is non-manifold, although you gave us the "cow_manifold.obj" created by MeshLab. I think the mesh is still not strictly manifold. 

Could you please check this?  Thanks very much!

Best,

Han

**Comment by yushiangw** [comment]
I guess it's caused by another reason, for example you can try libigl\tutorial\data\lilium.obj.
I will suggest use "-1*C" to avoid the problem of sorting smallest eigenvalue .
