### ISSUE TITLE
Issue with configuring practice 1

### ISSUE THREAD

**Issue by gardarsson** [smartgeometry-ucl/compM080-compGV18-2019#3]
I am using the CMake GUI to configure the project and get the following error message:

Creating target: igl::opengl_glfw_imgui (igl_opengl_glfw_imgui)
CMake Error at C:/Users/johan/OneDrive/UCL/Term 2/Acquisition and Processing of 3D Geometry/Tutorials/compM080-compGV18-2019/tutorial_001/cpp/libigl/cmake/DownloadProject.cmake:179 (message):
  Build step for libigl-imgui failed: 1
Call Stack (most recent call first):
  C:/Users/johan/OneDrive/UCL/Term 2/Acquisition and Processing of 3D Geometry/Tutorials/compM080-compGV18-2019/tutorial_001/cpp/libigl/cmake/LibiglDownloadExternal.cmake:14 (download_project)
  C:/Users/johan/OneDrive/UCL/Term 2/Acquisition and Processing of 3D Geometry/Tutorials/compM080-compGV18-2019/tutorial_001/cpp/libigl/cmake/LibiglDownloadExternal.cmake:90 (igl_download_project)
  C:/Users/johan/OneDrive/UCL/Term 2/Acquisition and Processing of 3D Geometry/Tutorials/compM080-compGV18-2019/tutorial_001/cpp/libigl/cmake/libigl.cmake:363 (igl_download_imgui)
  cmake/FindLIBIGL.cmake:36 (include)
  CMakeLists.txt:11 (find_package)

----------------------------------------
Any suggestions on how to fix this?

Thanks in advance!

**Comment by yushiangw** [comment]
probably caused by cmake cannot find libigl.
you can try to recheck 'getting libigl section' at
https://github.com/smartgeometry-ucl/compM080-compGV18-2019/tree/master/tutorial_001/cpp#i-get-libigl-via-git-submodule-or-git-clone

please post full cmake log if problem still exist.
