### ISSUE TITLE
Question on Libigl

### ISSUE THREAD

**Issue by hanyang1996** [smartgeometry-ucl/compM080-compGV18-2019#4]
Hi!

I have a question on using Libigl library.  Is it possible to download Libigl library only once and use it all the time? In tutorial 1 and 2, I found that each time I need to git clone the libigl to subfolder "cpp" for every single practice.  Can we download libigl to a specific folder and use it for all practices? If yes, how to do it?

Thanks!

Han

**Comment by yushiangw** [comment]
Hi, it's possible. Basically you just need to make sure cmake can find libigl, when you do `cmake` in the build directory.
You can take a look of **find_path(LIBIGL_INCLUDE_DIR** in 
https://github.com/smartgeometry-ucl/compM080-compGV18-2019/blob/master/tutorial_001/cpp/pratices_001/src/cmake/FindLIBIGL.cmake

we will also try to avoid redundancy in the future.

**Comment by hanyang1996** [comment]
Cool! 

Thanks!
