### ISSUE TITLE
Scan data not found in CPP Tutorial1 Practice2

### ISSUE THREAD

**Issue by YifanLiChina** [smartgeometry-ucl/compM080-compGV18-2019#5]
Hi, I am trying to go through the C++ practice and get stuck by the data problem as shown in the pictures. Any suggestions to fix it? Thanks very much.
Another thing is that due to the lack of background in C++, I find it quite obscure to even just follow the given solution. Could you @yushiangw add any comments to explain a little bit about how the code works? As C++ is also needed for my individual project, it would be really helpful! Thanks very much!!
![capture](https://user-images.githubusercontent.com/28495710/51871873-84dd6080-234f-11e9-9fa7-eec25e6cca36.PNG)
![capture1](https://user-images.githubusercontent.com/28495710/51871878-87d85100-234f-11e9-8a43-96473744f359.PNG)

**Comment by yushiangw** [comment]
Hi,
about data loading: please change input data's path at main.cpp#L318 to absolute path such as "/mydrive/compM080-compGV18-2019/tutorial_001/cpp/data/static_dock.sens".  then it should work.

not sure which part is confusing. The function will average each depth pixels across N frames. And avoid the pixel contains zero value. 
one complicated part is using a matrix (Q) as a mask to select pixels like the comment below.
// syntax hints:
	// Eigen 
	//  R = (Q.array() == 0).select(P, R) 
	// Numpy equivalent
	//  R[Q==0]=P[Q==0]
	// 
you can also use for-loop since it's c++ it will not create huge performance impact.

**Comment by YifanLiChina** [comment]
> Hi,
> about data loading: please change input data's path at main.cpp#L318 to absolute path such as "/mydrive/compM080-compGV18-2019/tutorial_001/cpp/data/static_dock.sens". then it should work.
> 
> not sure which part is confusing. The function will average each depth pixels across N frames. And avoid the pixel contains zero value.
> one complicated part is using a matrix (Q) as a mask to select pixels like the comment below.
> // syntax hints:
> // Eigen
> // R = (Q.array() == 0).select(P, R)
> // Numpy equivalent
> // R[Q==0]=P[Q==0]
> //
> you can also use for-loop since it's c++ it will not create huge performance impact.

Hi,

Thanks for your help! 

Absolute path can fix the not found problem. I actually tried it before but failed because I used '\'. Now with '/', it is working. I suppose '\\' should work as well.

About the equation: R = (Q.array() == 0).select(P, R)
Take the last line as an example: out_depth = (count_mat.array() != 0).select(mean_depth, zero_mat);
I am a bit confused about 'R', as it should be 'out_depth' which is left to '=', 
but in the right side, inside of the brackets, 'R' stands for 'zero_mat' now.
Could you explain what this line means? Thanks very much!

**Comment by yushiangw** [comment]
Each pixel may have different # of valid pixels so you need to record a count. and the line `out_depth = (count_mat.array() != 0).select(mean_depth, zero_mat);` is trying to reset a pixel value to zero if it does not have any valid pixel. (count=0) 

This `select` function is coming from C/C++'s inline if-else. e.g. x = (condition) > value_1 ? value_2;
you are welcome to our office if this example is still hard to understand.
