### ISSUE TITLE
How to change the cmakelist.txt ??

### ISSUE THREAD

**Issue by FoxinSnow** [smartgeometry-ucl/compM080-compGV18-2019#7]
I try to build a new project with libigl. I put libigl in user/local/igl/libigl. I put libigl in user/local/include/igl. I put libigl in my new project dictionary. But I all got feedback that "can not find igl". I think it may because I need to rewrite cmakelist file. But do you have any advise on how to do this? Thank you.

**Comment by FoxinSnow** [comment]
Here is the information about the error.


libigl not found --- You can download it using:

  	git clone --recursive https://github.com/libigl/libigl.git
  /Users/fei07/Documents/Atom/compM080-compGV18-2019/course_work_1/cw1/src/../libigl
  (missing: LIBIGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.13.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLIBIGL.cmake:26 (find_package_handle_standard_args)
  CMakeLists.txt:11 (find_package)

**Comment by yushiangw** [comment]
Hi,
which tutorial you are trying to build?
Have you tried #4 and https://github.com/smartgeometry-ucl/compM080-compGV18-2019/tree/master/tutorial_002/cpp#step-2-get-libigl ?

**Comment by FoxinSnow** [comment]
Hi.
I can run all the examples in the tutorial 001 and tutorial 002. But I want to build a new project with libigl. I also copy the findIGL and cmakelist to my new project. And I changed the project name in camkelist. But I still can not run the new project.

**Comment by yushiangw** [comment]
i guess you need to delete your cmake cache and retry.
cmake should search the path indicated in the FindLIBIGL.cmake
other option is to fill in libigl's path in cmake's gui after the failed configuration (if you can access cmake-gui)

**Comment by FoxinSnow** [comment]
Hi I figure the problem with a friend. I need to change path searching in the FindIGL.cmake file. Then it can find my igl. Original FindIGL.camke file seems not include all possible roots. Thank you!

**Comment by yushiangw** [comment]
glad to hear you resolved the issue.
