### ISSUE TITLE
Problem with KDTree in Python

### ISSUE THREAD

**Issue by LexRillo** [smartgeometry-ucl/compM080-compGV18-2019#8]
when trying to use the KDTree in the following way

```
pcd_tree = KDTreeFlann(Q)
print(type(pcd_tree))   ##<class 'open3d.open3d.geometry.KDTreeFlann'>
print(type(P))  ## <class 'numpy.ndarray'>
interim_pc = Vector3dVector(P)
[k, idx, i] = pcd_tree.search_knn_vector_3d(interim_pc[15], 1)
```

it results in the following error:

> RuntimeError: search_knn_vector_3d() error!

I have tried with other versions of the code like:
`[k, idx, i] = pcd_tree.search_knn_vector_3d(interim_pc, 1)
`
but it errors out like:

> TypeError: search_knn_vector_3d(): incompatible function arguments. The following argument types are supported:
>     1. (self: open3d.open3d.geometry.KDTreeFlann, query: numpy.ndarray[float64[3, 1]], knn: int) -> Tuple[int, open3d.open3d.IntVector, open3d.open3d.DoubleVector]
> 
> Invoked with: <open3d.open3d.geometry.KDTreeFlann object at 0x000002835A873AE8>, std::vector<Eigen::Vector3d> with 40097 elements.
> Use numpy.asarray() to access data., 1
> 
> Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
> <pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
> conversions are optional and require extra headers to be included
> when compiling your pybind11 module.

I am not sure what to do. I am using the code differently than the one used in the tutorial but the documentation is not very helpful since it is mostly wrappers of C++ functions

**Comment by yushiangw** [comment]
could you try scikit ?
https://scikit-learn.org/stable/modules/neighbors.html#finding-the-nearest-neighbors

**Comment by LexRillo** [comment]
I tried this code:

`nbrs = NearestNeighbors(n_neighbors=2, algorithm='kd_tree').fit(pcd_tree)`

but it returned 

> TypeError: float() argument must be a string or a number, not 'open3d.open3d.geometry.KDTreeFlann'

**Comment by LexRillo** [comment]
Ok I think I figure this out

```
q_pc = Vector3dVector(Q)
interim_pc = Vector3dVector(P)
nbrs = NearestNeighbors(n_neighbors=2, algorithm='kd_tree').fit(q_pc)
distances, indices = nbrs.kneighbors(interim_pc)
```
Is this what you were asking me to try? Is this allowed?

**Comment by preddy5** [comment]
Hey @LexRillo ,
intermic[15] doesnt return a vector
could you try

`[k, idx, i] = pcd_tree.search_knn_vector_3d(P[15], 1)
`
or
```
pcd2 = PointCloud()
pcd2.points = interim_pc
[k, idx, i] = pcd_tree.search_knn_vector_3d(pcd2.points[15], 1)

```

**Comment by LexRillo** [comment]
Both of them code pieces give:

> RuntimeError: search_knn_vector_3d() error!

But the suggestion from yushiangw does work. Is Nearest Neighbors from sklearn allowed?

**Comment by preddy5** [comment]
Yes @LexRillo, Nearest Neighbors in sklearn in allowed.
I am unable to reproduce the issue :/ I would appreciate it if you could forward the script to my personal e-mail for future reference. 

Thanks

**Comment by LexRillo** [comment]
Ok. I will do so.
